# Generated by Django 3.2.23 on 2024-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
