# Generated by Django 3.2.23 on 2024-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricingconfig_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
