# Generated by Django 3.2.23 on 2024-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricingconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
