# Generated by Django 3.2.23 on 2024-01-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricingconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
